UEFI_INC = -I${EDK2_ROOT}/MdePkg/Include \
	-I${EDK2_ROOT}/MdePkg/Include/X64

CPPFLAGS = -I${NEWLIB_INCDIR} $$(UEFI_INC) -nostdlib

CFLAGS = -g --target=x86_64-none-elf -mno-red-zone -Wall -masm=intel
CXXFLAGS = $$(CFLAGS) -std=c++1z -fno-rtti -fno-exceptions

MAKE    = make
CC      = clang-4.0
CXX     = clang++-4.0
LD      = ld
OBJCOPY = objcopy
QEMU    = qemu-system-x86_64

OVMF_CODE = ${OVMF_CODE}
OVMF_VARS = ${OVMF_VARS}
BOOTLOADER = ${BOOTLOADER}

DISKIMAGE = ${DISKIMAGE}
USB_MOUNT_POINT = /mnt/usb
